### ISSUE TITLE
VICE (ROD) INSECT GLAIVE ADDRESS

### ISSUE THREAD

**Issue by agungarifr** [ZephyAlurus/MHW-Texture-Editing-Documentation#1]
hi, 
i checked the rod007 = Temptation's Trident + Vice (Odogaron) is no longer valid.
it is replaced by jho's glaive atm.

there must be another miss within rod's addresses

**Comment by AsteriskAmpersand** [comment]
You were correct, no idea if those id were ever correct. IDs were off by one from entry 5 onwards for the insect glaive.

This has been fixed. Thanks for your input. Marking it as closed now.
